name: Haskell CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  stack:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      runs-on: ${{ matrix.os }}
      steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-haskell@v1
        with:
          stack-version: 'latest'
      - name: Init
        run: stack init --resolver lts-14.27
      - name: Build
        run: stack build
      - name: Run tests with Stack
        run: stack test
  cabal:
    strategy: 
      matrix: 
        ghc: [8.6.5, 8.8.3, 8.10.1]
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: 'latest'

    - name: Cache
      uses: actions/cache@v1
      env:
        cache-name: cache-cabal
      with:
        path: ~/.cabal
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    
    - name: Update
      run: cabal new-update
    - name: Configure
      run: cabal new-configure --enable-tests
    - name: Build 
      run: cabal new-build --enable-tests
    - name: Run tests with Cabal
      run: cabal new-test --test-show-details=streaming
